export const mockedDeliveries = [
  {
    client: 'Kub - Heidenreich',
    customer: {
      name: 'Dr. Roosevelt Balistreri',
      address: '0539 Brakus Vista',
      city: 'Missoula',
      zipCode: '61131',
      latitude: '2.1774',
      longitude: '38.0264',
    },
    delivery: { status: 'delivered', latitude: '41.4105', longitude: '2.1741' },
    id: '1',
    active: false,
  },
  {
    client: 'Tremblay Inc',
    customer: {
      name: 'Pam Rutherford II',
      address: '386 Litzy Freeway',
      city: 'Richland',
      zipCode: '09359',
      latitude: '57.4017',
      longitude: '-117.7411',
    },
    delivery: { status: 'delivered' },
    id: '2',
    active: false,
  },
  {
    client: 'Moore Group',
    customer: {
      name: 'Courtney Kuvalis',
      address: '1596 Simonis Extension',
      city: 'Yakima',
      zipCode: '81325',
      latitude: '77.2300',
      longitude: '-101.1915',
    },
    delivery: { status: 'delivered' },
    id: '3',
    active: false,
  },
  {
    client: 'Powlowski, Ebert and Raynor',
    customer: {
      name: 'Dennis Sauer',
      address: '850 Dicki Views',
      city: 'Orem',
      zipCode: '21979-7782',
      latitude: '6.9559',
      longitude: '10.3099',
    },
    delivery: {
      status: 'delivered',
      longitude: '2.1570655',
      latitude: '41.375802',
    },
    id: '4',
  },
  {
    client: 'Goyette, Cormier and Kirlin',
    customer: {
      name: 'Sonia Walsh',
      address: '90859 Mertz Locks',
      city: 'Waco',
      zipCode: '31634-8519',
      latitude: '-89.0245',
      longitude: '-38.4329',
    },
    delivery: { status: 'delivered', latitude: '41.4105', longitude: '2.1741' },
    id: '5',
    active: false,
  },
  {
    client: 'Mohr LLC',
    customer: {
      name: 'Scott Jacobson II',
      address: '785 Heidenreich Centers',
      city: 'Chico',
      zipCode: '11757',
      latitude: '-39.5984',
      longitude: '97.4351',
    },
    delivery: { status: 'delivered' },
    id: '6',
    active: false,
  },
  {
    client: 'Shields, Cremin and Schmidt',
    customer: {
      name: 'Jeanette Marvin',
      address: '198 Wehner Square',
      city: 'Camarillo',
      zipCode: '18654',
      latitude: '52.4477',
      longitude: '127.3446',
    },
    delivery: {
      status: 'delivered',
      latitude: 42.8539904,
      longitude: 20.9518592,
    },
    id: '7',
    active: false,
  },
  {
    client: 'Ankunding, Rogahn and Bode',
    customer: {
      name: 'Matt Fisher',
      address: '8930 Ziemann Villages',
      city: 'Long Beach',
      zipCode: '92031-6793',
      latitude: '-78.1478',
      longitude: '-104.5115',
    },
    delivery: { status: 'delivered', latitude: 1, longitude: 1 },
    id: '8',
    active: true,
  },
  {
    client: 'Jones, Daugherty and Weissnat',
    customer: {
      name: 'Jake Dare',
      address: '8848 Collier Pines',
      city: 'Walnut Creek',
      zipCode: '16097',
      latitude: '-50.2408',
      longitude: '-40.0654',
    },
    delivery: { status: 'delivered', latitude: 1, longitude: 1 },
    id: '9',
  },
  {
    client: 'Barton - Feeney',
    customer: {
      name: 'Josh Corkery',
      address: '5408 Larson Hills',
      city: 'San Diego',
      zipCode: '66318',
      latitude: '-78.3820',
      longitude: '13.0379',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '10',
  },
  {
    client: 'Davis, Ebert and Brekke',
    customer: {
      name: 'Dallas Hane DVM',
      address: '6694 Carleton Spurs',
      city: 'New Britain',
      zipCode: '59964-7096',
      latitude: '-77.2365',
      longitude: '-3.9466',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '11',
  },
  {
    client: 'Kshlerin LLC',
    customer: {
      name: 'Linda Beer',
      address: '720 Bernier Mall',
      city: 'Kentwood',
      zipCode: '96981-0413',
      latitude: '-58.4466',
      longitude: '-150.1146',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '12',
  },
  {
    client: 'Kuhn and Sons',
    customer: {
      name: 'Josefina Swift',
      address: '190 Kuvalis Wells',
      city: 'North Bethesda',
      zipCode: '63638-0512',
      latitude: '72.7328',
      longitude: '-62.3456',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '13',
  },
  {
    client: 'Denesik - Rice',
    customer: {
      name: 'Allen Welch IV',
      address: '3618 Jevon Oval',
      city: 'Kansas City',
      zipCode: '45555-6583',
      latitude: '34.0658',
      longitude: '9.3647',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '14',
  },
  {
    client: 'Runolfsson and Sons',
    customer: {
      name: 'Jerry Jacobson',
      address: '49270 Morar Shoal',
      city: 'Rochester Hills',
      zipCode: '10550-2345',
      latitude: '44.7639',
      longitude: '45.0379',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '15',
  },
  {
    client: 'Spencer, Koss and Kutch',
    customer: {
      name: 'Mrs. Jodi Dicki',
      address: '8732 Tromp Ramp',
      city: 'Garland',
      zipCode: '15662-2189',
      latitude: '-66.7393',
      longitude: '-64.0528',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '16',
  },
  {
    client: 'Ryan and Sons',
    customer: {
      name: 'Edna Morar',
      address: '60122 Elenora Tunnel',
      city: 'Upland',
      zipCode: '53893-5914',
      latitude: '88.1181',
      longitude: '130.9235',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '17',
  },
  {
    client: 'Spencer - Lehner',
    customer: {
      name: 'Kay Gutkowski',
      address: '49918 Javonte Meadow',
      city: 'Fargo',
      zipCode: '35637',
      latitude: '45.6138',
      longitude: '-151.4226',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '18',
  },
  {
    client: 'McKenzie, Mohr and Rempel',
    customer: {
      name: 'Gretchen Aufderhar',
      address: '610 Annabell Fort',
      city: 'Eagan',
      zipCode: '86583-3893',
      latitude: '35.8528',
      longitude: '-125.3061',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '19',
  },
  {
    client: 'Frami, Kutch and Wolf',
    customer: {
      name: 'Diana MacGyver',
      address: '9379 Noemie Plaza',
      city: 'Syracuse',
      zipCode: '56943',
      latitude: '83.0908',
      longitude: '-7.9169',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '20',
  },
  {
    client: 'Schmidt - Kiehn',
    customer: {
      name: 'Teresa Herman',
      address: '88016 Brakus Run',
      city: 'Stockton',
      zipCode: '57015-8171',
      latitude: '-5.0934',
      longitude: '58.6129',
    },
    delivery: { status: 'delivered', latitude: 1, longitude: 1 },
    id: '21',
  },
  {
    client: 'Dooley and Sons',
    customer: {
      name: 'Miss Lynn Mohr',
      address: '0826 Maximo Lights',
      city: 'Encinitas',
      zipCode: '30555',
      latitude: '7.2964',
      longitude: '17.9771',
    },
    delivery: { status: 'delivered', latitude: 1, longitude: 1 },
    id: '22',
  },
  {
    client: 'Moore, Farrell and Johnson',
    customer: {
      name: 'Krystal VonRueden',
      address: '73230 Kristian Cove',
      city: 'Freeport',
      zipCode: '45790',
      latitude: '-54.9865',
      longitude: '-29.6371',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '23',
  },
  {
    client: 'Hahn - Haag',
    customer: {
      name: 'Belinda Schoen',
      address: '3449 Arnulfo Trail',
      city: 'Round Rock',
      zipCode: '27246-6614',
      latitude: '29.4182',
      longitude: '38.3658',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '24',
  },
  {
    client: 'Batz, Barrows and Carter',
    customer: {
      name: 'Melba Tremblay Sr.',
      address: '1525 Dora Lane',
      city: 'Medford',
      zipCode: '62379',
      latitude: '14.8309',
      longitude: '92.1361',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '25',
  },
  {
    client: 'Wunsch - Dare',
    customer: {
      name: 'Samantha Kreiger',
      address: '3699 Fredrick Mount',
      city: 'Sacramento',
      zipCode: '98538',
      latitude: '68.0629',
      longitude: '109.0342',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '26',
  },
  {
    client: 'Marquardt - Hegmann',
    customer: {
      name: 'Gayle Stracke',
      address: '8340 Afton Shore',
      city: 'Jacksonville',
      zipCode: '61766-3313',
      latitude: '-89.8651',
      longitude: '179.2009',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '27',
  },
  {
    client: 'Altenwerth - Reinger',
    customer: {
      name: 'Belinda Johns',
      address: '01953 Howe Vista',
      city: 'Troy',
      zipCode: '99980-2309',
      latitude: '-19.7077',
      longitude: '-63.0907',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '28',
  },
  {
    client: 'Wintheiser LLC',
    customer: {
      name: 'Mamie Windler',
      address: '21286 Mayer Oval',
      city: 'Apex',
      zipCode: '59535',
      latitude: '-86.5978',
      longitude: '-65.8563',
    },
    delivery: { status: 'delivered', latitude: 1, longitude: 1 },
    id: '29',
    status: 'delivered',
    latitude: 1,
    longitude: 1,
  },
  {
    client: 'Kiehn and Sons',
    customer: {
      name: 'Jean Bruen DDS',
      address: '4186 Agustin Mission',
      city: 'Portsmouth',
      zipCode: '66548',
      latitude: '-66.2670',
      longitude: '-160.9926',
    },
    delivery: { status: 'delivered', latitude: 1, longitude: 2 },
    id: '30',
    status: 'delivered',
    latitude: 1,
    longitude: 2,
  },
  {
    client: 'Mertz, Goldner and Langosh',
    customer: {
      name: 'Lawrence Leannon',
      address: '40685 Hansen Landing',
      city: 'Oak Lawn',
      zipCode: '18568',
      latitude: '49.8990',
      longitude: '-130.7359',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '31',
  },
  {
    client: 'Wuckert - Wunsch',
    customer: {
      name: 'Casey Hoppe',
      address: '62266 Hagenes Plains',
      city: 'Mount Pleasant',
      zipCode: '94115-2939',
      latitude: '45.0040',
      longitude: '130.2299',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '32',
  },
  {
    client: 'Heller - Blick',
    customer: {
      name: 'Miss Jeffrey Zboncak',
      address: '82574 Fadel Isle',
      city: 'Delano',
      zipCode: '11115-3857',
      latitude: '16.7956',
      longitude: '-133.2994',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '33',
  },
  {
    client: 'Fay - Schroeder',
    customer: {
      name: 'Mabel Kemmer V',
      address: '1813 Howe Ridges',
      city: 'Cambridge',
      zipCode: '60929',
      latitude: '-81.9037',
      longitude: '-175.4254',
    },
    delivery: {
      status: 'delivered',
      latitude: 42.8539904,
      longitude: 20.9518592,
    },
    id: '34',
  },
  {
    client: 'Harber Inc',
    customer: {
      name: 'Mrs. Lora Rogahn',
      address: '1664 Obie Passage',
      city: 'Charleston',
      zipCode: '76678-7656',
      latitude: '29.6101',
      longitude: '81.0677',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '35',
  },
  {
    client: 'Mills - Koepp',
    customer: {
      name: 'Victor Rosenbaum',
      address: '116 Ansley Wells',
      city: 'Medford',
      zipCode: '99928-6408',
      latitude: '-42.8602',
      longitude: '-165.5189',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '36',
  },
  {
    client: 'Waelchi, Boehm and Streich',
    customer: {
      name: 'Pat Goodwin',
      address: '912 Robel Prairie',
      city: 'Shawnee',
      zipCode: '22271',
      latitude: '13.9446',
      longitude: '-77.7196',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '37',
  },
  {
    client: 'Ferry, Harber and Hackett',
    customer: {
      name: 'Ms. Dianna Satterfield',
      address: '85920 Roob Trafficway',
      city: 'Dunwoody',
      zipCode: '29745-2981',
      latitude: '38.8727',
      longitude: '7.2162',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '38',
  },
  {
    client: 'Williamson - Runte',
    customer: {
      name: 'Maggie Koepp',
      address: '142 Hollie Fort',
      city: 'South Jordan',
      zipCode: '18479-4363',
      latitude: '11.1936',
      longitude: '-74.1561',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '39',
  },
  {
    client: 'Monahan Group',
    customer: {
      name: 'Andy Kutch',
      address: '41447 Deonte Trafficway',
      city: 'Portsmouth',
      zipCode: '63687-3804',
      latitude: '1.7407',
      longitude: '27.2674',
    },
    delivery: { status: 'delivered', latitude: 1, longitude: 1 },
    id: '40',
  },
  {
    client: "Torp, D'Amore and Runolfsson",
    customer: {
      name: 'Flora McKenzie',
      address: '898 Rosie Centers',
      city: 'Kearny',
      zipCode: '43991-7540',
      latitude: '58.0671',
      longitude: '63.7026',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '41',
  },
  {
    client: "O'Kon and Sons",
    customer: {
      name: 'Adrian Bradtke',
      address: '8631 Schroeder Forks',
      city: 'Lakewood',
      zipCode: '54171',
      latitude: '71.6306',
      longitude: '-57.6724',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '42',
  },
  {
    client: 'Pollich, Kuvalis and Senger',
    customer: {
      name: 'Rodney Nolan',
      address: '2979 Pansy Common',
      city: 'San Marcos',
      zipCode: '03587-3904',
      latitude: '32.8938',
      longitude: '75.9055',
    },
    delivery: { status: 'delivered', latitude: 1, longitude: 1 },
    id: '43',
  },
  {
    client: 'Conroy Group',
    customer: {
      name: 'Adrian Davis',
      address: '122 Considine Flat',
      city: 'Tacoma',
      zipCode: '18398',
      latitude: '71.3742',
      longitude: '-5.8945',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '44',
  },
  {
    client: 'Hessel Inc',
    customer: {
      name: 'Nicolas Rice',
      address: '58569 Conn Stravenue',
      city: 'Union City',
      zipCode: '67378',
      latitude: '-3.8278',
      longitude: '-117.1571',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '45',
  },
  {
    client: 'Bernhard LLC',
    customer: {
      name: 'Roy Stokes DVM',
      address: '51298 Bode Trafficway',
      city: 'Catonsville',
      zipCode: '38212',
      latitude: '29.1723',
      longitude: '-168.8414',
    },
    delivery: { status: 'delivered', latitude: 1, longitude: 1 },
    id: '46',
  },
  {
    client: 'Heidenreich - Reichert',
    customer: {
      name: 'Lynette Kshlerin',
      address: '51345 Douglas Lane',
      city: 'Grand Junction',
      zipCode: '85407-8371',
      latitude: '-37.4717',
      longitude: '-39.2160',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '47',
  },
  {
    client: 'Kling, McDermott and Grimes',
    customer: {
      name: 'Connie Durgan',
      address: '1203 Skiles Ports',
      city: 'Citrus Heights',
      zipCode: '41598',
      latitude: '-14.1584',
      longitude: '25.5460',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '48',
  },
  {
    client: 'Schulist Inc',
    customer: {
      name: 'Colin Gleason',
      address: '197 Dibbert Crossing',
      city: 'Wichita',
      zipCode: '88719-3265',
      latitude: '18.5768',
      longitude: '174.7264',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '49',
  },
  {
    client: 'Ullrich - Erdman',
    customer: {
      name: 'Simon Jaskolski',
      address: '3703 Wendell Summit',
      city: 'Maricopa',
      zipCode: '38720-7149',
      latitude: '34.5217',
      longitude: '-176.0657',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '50',
  },
  {
    client: 'Koss - Pacocha',
    customer: {
      name: 'Amelia Bode',
      address: '6180 Demarco Wells',
      city: 'Fayetteville',
      zipCode: '41860',
      latitude: '-67.7368',
      longitude: '51.1227',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '51',
  },
  {
    client: 'Osinski, Roob and Lang',
    customer: {
      name: 'Ted Steuber',
      address: '8670 Michele Mission',
      city: 'Springdale',
      zipCode: '97456',
      latitude: '10.5698',
      longitude: '119.9738',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '52',
  },
  {
    client: 'Stark - Kuhlman',
    customer: {
      name: 'Andrea Schiller',
      address: '7746 Reichel Loop',
      city: 'Los Angeles',
      zipCode: '75763-6784',
      latitude: '28.9107',
      longitude: '44.1511',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '53',
    status: 'delivered',
    latitude: 1,
    longitude: 2,
  },
  {
    client: 'Dicki, Schmeler and Stark',
    customer: {
      name: 'Everett Douglas',
      address: '8617 Breitenberg Inlet',
      city: 'Murray',
      zipCode: '85970',
      latitude: '-48.2128',
      longitude: '20.6770',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '54',
  },
  {
    client: 'Littel Group',
    customer: {
      name: 'Rick Mraz I',
      address: '06262 Dejon View',
      city: 'Hattiesburg',
      zipCode: '17443',
      latitude: '0.5666',
      longitude: '100.9389',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '55',
  },
  {
    client: 'Morissette - Skiles',
    customer: {
      name: 'Bruce Yundt IV',
      address: '1050 Alec Shoal',
      city: 'Cheyenne',
      zipCode: '40820-8652',
      latitude: '-50.7101',
      longitude: '-152.5144',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '56',
  },
  {
    client: 'Beer - Hickle',
    customer: {
      name: 'Lee Bartoletti',
      address: '5171 Gutmann Keys',
      city: 'Miramar',
      zipCode: '85249',
      latitude: '-75.2265',
      longitude: '37.1172',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '57',
  },
  {
    client: 'Renner and Sons',
    customer: {
      name: 'Hope Lemke',
      address: '46197 Moen Island',
      city: 'Placentia',
      zipCode: '70739',
      latitude: '16.7796',
      longitude: '-115.1131',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '58',
  },
  {
    client: 'Quigley, Schultz and Satterfield',
    customer: {
      name: 'Audrey Herman',
      address: '73509 Runte Mountain',
      city: 'Bristol',
      zipCode: '06639-4106',
      latitude: '86.3413',
      longitude: '2.7590',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '59',
  },
  {
    client: 'Mertz, Satterfield and Wiza',
    customer: {
      name: 'Ted Nader',
      address: '772 Valentin Roads',
      city: 'Sacramento',
      zipCode: '95030-3242',
      latitude: '-85.0478',
      longitude: '46.7518',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '60',
  },
  {
    client: 'Volkman, Batz and Kris',
    customer: {
      name: 'Miss Amy Roberts',
      address: '51807 Filomena Oval',
      city: 'Lynn',
      zipCode: '20344',
      latitude: '-39.2401',
      longitude: '-120.4572',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '61',
  },
  {
    client: 'Bailey, Cruickshank and Leannon',
    customer: {
      name: 'Gloria Bailey',
      address: '056 Hoppe Dale',
      city: 'Victoria',
      zipCode: '19879',
      latitude: '-53.8230',
      longitude: '-74.6167',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '62',
  },
  {
    client: 'Jacobi - Ankunding',
    customer: {
      name: 'Roderick Langosh',
      address: '8603 Steuber Trail',
      city: 'Sandy',
      zipCode: '20868',
      latitude: '-79.1645',
      longitude: '140.7055',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '63',
  },
  {
    client: 'Schoen - Steuber',
    customer: {
      name: 'Dora Bogan',
      address: '878 Pouros Lodge',
      city: 'Cicero',
      zipCode: '90327',
      latitude: '-8.1471',
      longitude: '-8.8690',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '64',
  },
  {
    client: 'Thiel - Greenholt',
    customer: {
      name: 'Jerome Grimes',
      address: '70081 Jenkins Route',
      city: 'North Lauderdale',
      zipCode: '55654-8618',
      latitude: '78.4404',
      longitude: '57.3324',
    },
    delivery: { status: 'delivered', latitude: 1, longitude: 1 },
    id: '65',
  },
  {
    client: 'Kertzmann - Carter',
    customer: {
      name: 'Luz Heathcote',
      address: '915 Lind Club',
      city: 'Irving',
      zipCode: '25910-9197',
      latitude: '48.4487',
      longitude: '-107.8430',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '66',
  },
  {
    client: 'Stark, Schmeler and Ritchie',
    customer: {
      name: 'Winston Beahan',
      address: '460 Ervin Ports',
      city: 'Decatur',
      zipCode: '98323',
      latitude: '21.9172',
      longitude: '-129.8514',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '67',
  },
  {
    client: 'Herman and Sons',
    customer: {
      name: 'Mr. Charlie Padberg',
      address: '60058 Effertz Camp',
      city: 'Dallas',
      zipCode: '10650',
      latitude: '44.9607',
      longitude: '-146.4037',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '68',
  },
  {
    client: 'Fay, Towne and Satterfield',
    customer: {
      name: 'Cory Glover',
      address: '27438 McKenzie Crescent',
      city: 'Mobile',
      zipCode: '90965-5666',
      latitude: '42.1890',
      longitude: '-81.4266',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '69',
  },
  {
    client: 'Bahringer, Bernier and Hintz',
    customer: {
      name: 'Walter Reynolds',
      address: '0975 Nienow Spurs',
      city: 'San Buenaventura (Ventura)',
      zipCode: '49604',
      latitude: '-40.1549',
      longitude: '150.5867',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '70',
  },
  {
    client: 'Satterfield - Fritsch',
    customer: {
      name: 'James Macejkovic',
      address: '579 Sigmund Valleys',
      city: 'Upland',
      zipCode: '24786-1368',
      latitude: '-82.6969',
      longitude: '85.3846',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '71',
  },
  {
    client: 'Greenfelder - Nicolas',
    customer: {
      name: 'Natalie Koelpin',
      address: '7894 Michele View',
      city: 'Santa Barbara',
      zipCode: '29084',
      latitude: '-25.9013',
      longitude: '23.8081',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '72',
  },
  {
    client: 'Kerluke - Prosacco',
    customer: {
      name: 'Mr. Sadie Stoltenberg',
      address: '7833 Garret Viaduct',
      city: 'West Valley City',
      zipCode: '35593',
      latitude: '-85.3747',
      longitude: '88.9574',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '73',
  },
  {
    client: 'Armstrong Group',
    customer: {
      name: 'Angelina Hermiston',
      address: '3736 Schaefer Lakes',
      city: 'Turlock',
      zipCode: '20649',
      latitude: '53.5993',
      longitude: '-161.7948',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '74',
  },
  {
    client: 'Reinger Group',
    customer: {
      name: 'Lynn Schulist',
      address: '68345 Nelson Throughway',
      city: 'Skokie',
      zipCode: '84535-7663',
      latitude: '74.0406',
      longitude: '15.7105',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '75',
  },
  {
    client: 'Gislason - Pagac',
    customer: {
      name: 'Deborah Stanton',
      address: '06974 Imelda Dale',
      city: 'Stratford',
      zipCode: '25161',
      latitude: '40.3152',
      longitude: '-81.5726',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '76',
  },
  {
    client: 'Block, Rath and Breitenberg',
    customer: {
      name: 'Shannon Stracke',
      address: '4536 Davis Stream',
      city: 'Farmington',
      zipCode: '72530',
      latitude: '-75.7794',
      longitude: '-146.0771',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '77',
  },
  {
    client: 'Howell - Bayer',
    customer: {
      name: 'Hubert Blanda',
      address: '7847 Bode Vista',
      city: 'Schenectady',
      zipCode: '58222',
      latitude: '-88.1515',
      longitude: '34.4340',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '78',
  },
  {
    client: 'Bernhard, Lakin and Olson',
    customer: {
      name: 'Angela Cruickshank II',
      address: '30438 Kemmer Streets',
      city: 'Pine Bluff',
      zipCode: '50230',
      latitude: '34.7844',
      longitude: '-53.9125',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '79',
  },
  {
    client: 'Wintheiser and Sons',
    customer: {
      name: 'Domingo Nicolas',
      address: '87886 Leta Shoal',
      city: 'La Crosse',
      zipCode: '51544-3647',
      latitude: '-45.7125',
      longitude: '91.3314',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '80',
  },
  {
    client: 'Hane, Grimes and Cartwright',
    customer: {
      name: 'Gail Bauch',
      address: '768 Gottlieb Orchard',
      city: 'Detroit',
      zipCode: '56984-9594',
      latitude: '38.3142',
      longitude: '-157.4127',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '81',
  },
  {
    client: 'Predovic LLC',
    customer: {
      name: 'Kristine Fadel',
      address: '67054 Novella Place',
      city: 'Lake Ridge',
      zipCode: '11791',
      latitude: '70.3949',
      longitude: '17.6503',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '82',
  },
  {
    client: 'Schulist and Sons',
    customer: {
      name: 'Randolph Nitzsche',
      address: '19672 Trisha Mission',
      city: 'Beaverton',
      zipCode: '97047',
      latitude: '-74.4779',
      longitude: '-9.0057',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '83',
  },
  {
    client: 'Kihn Inc',
    customer: {
      name: 'Leslie Schiller V',
      address: '24786 Bernhard Drives',
      city: 'Dublin',
      zipCode: '20941-6018',
      latitude: '-23.3235',
      longitude: '155.6761',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '84',
  },
  {
    client: 'Stiedemann LLC',
    customer: {
      name: 'Kay Harris',
      address: '073 Stan Fall',
      city: 'Ponce',
      zipCode: '75040',
      latitude: '45.2901',
      longitude: '113.6406',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '85',
  },
  {
    client: 'Huel - Cummings',
    customer: {
      name: 'Jana Bailey',
      address: '66538 Greenholt Pass',
      city: 'Barnstable Town',
      zipCode: '65426-9315',
      latitude: '-19.0272',
      longitude: '-116.2325',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '86',
  },
  {
    client: 'Hackett, Keebler and Blick',
    customer: {
      name: 'Marty Ryan',
      address: '48192 Katherine Circles',
      city: 'Taunton',
      zipCode: '50778',
      latitude: '53.5407',
      longitude: '-93.6824',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '87',
  },
  {
    client: 'Mann Group',
    customer: {
      name: 'Caroline Moen',
      address: '0433 Jany Viaduct',
      city: 'South San Francisco',
      zipCode: '10212',
      latitude: '-53.8451',
      longitude: '-69.8137',
    },
    delivery: {
      status: 'delivered',
      latitude: 42.8539904,
      longitude: 20.9518592,
    },
    id: '88',
  },
  {
    client: 'Macejkovic, Turcotte and Gaylord',
    customer: {
      name: 'Geraldine Funk',
      address: '99163 Mitchell Tunnel',
      city: 'Odessa',
      zipCode: '00159',
      latitude: '11.9611',
      longitude: '-125.4747',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '89',
  },
  {
    client: 'Ebert - Stokes',
    customer: {
      name: 'Edgar Schowalter',
      address: '2606 Runte Junctions',
      city: 'Hammond',
      zipCode: '56209',
      latitude: '39.8420',
      longitude: '139.2004',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '90',
  },
  {
    client: 'Rohan - Bernhard',
    customer: {
      name: 'Dale Stark',
      address: '99921 Korey Station',
      city: 'Thousand Oaks',
      zipCode: '39075-1194',
      latitude: '-65.9758',
      longitude: '139.5904',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '91',
  },
  {
    client: "O'Conner Inc",
    customer: {
      name: 'Edith Turcotte II',
      address: '798 Muriel Street',
      city: 'East Honolulu',
      zipCode: '03969-5584',
      latitude: '32.3152',
      longitude: '-75.1969',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '92',
  },
  {
    client: 'McDermott, Wuckert and Collins',
    customer: {
      name: 'Barbara Baumbach',
      address: '9331 Crooks Greens',
      city: 'Victorville',
      zipCode: '51595',
      latitude: '53.6971',
      longitude: '159.9960',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '93',
  },
  {
    client: 'Emmerich, Funk and Beahan',
    customer: {
      name: 'Rosemarie Anderson',
      address: '037 Adella Points',
      city: 'Riverton',
      zipCode: '44514',
      latitude: '-63.2557',
      longitude: '-147.5806',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '94',
  },
  {
    client: 'Jerde LLC',
    customer: {
      name: 'Joshua Borer',
      address: '6540 Schmitt Isle',
      city: 'Cutler Bay',
      zipCode: '22377-7250',
      latitude: '-73.3854',
      longitude: '-60.3460',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '95',
  },
  {
    client: 'Pfeffer Group',
    customer: {
      name: 'Muriel Ebert',
      address: '37810 Audrey Manors',
      city: 'East Lansing',
      zipCode: '30353-9656',
      latitude: '71.1863',
      longitude: '-4.9328',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '96',
  },
  {
    client: 'Murazik - Mills',
    customer: {
      name: 'Aaron Hermiston DDS',
      address: '7467 Lincoln Union',
      city: 'Chapel Hill',
      zipCode: '31244-2534',
      latitude: '-61.0226',
      longitude: '-8.0135',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '97',
  },
  {
    client: 'Sipes - Murray',
    customer: {
      name: 'Alma Smitham',
      address: '06993 Sylvan Village',
      city: 'Port Charlotte',
      zipCode: '88208-4915',
      latitude: '-22.4592',
      longitude: '46.1369',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '98',
  },
  {
    client: 'Reichel - Harber',
    customer: {
      name: 'Rhonda Harris',
      address: '74523 Greenholt Landing',
      city: 'Union City',
      zipCode: '61859',
      latitude: '-49.3457',
      longitude: '79.8554',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '99',
  },
  {
    client: 'Ullrich - Krajcik',
    customer: {
      name: 'Audrey Farrell',
      address: '267 Schmeler Flats',
      city: 'East Honolulu',
      zipCode: '11925-4812',
      latitude: '-4.6590',
      longitude: '129.9894',
    },
    delivery: { status: 'idle', latitude: null, longitude: null },
    id: '100',
  },
];

export const MockDeliveriesStore = {
  deliveries: mockedDeliveries,
  loading: false,
  error: null,
};
