export enum ActionType {
  FETCH_DELIVERIES_LOADING = 'FETCH_DELIVERIES_LOADING',
  FETCH_DELIVERIES_SUCCESS = 'FETCH_DELIVERIES_SUCCESS',
  FETCH_DELIVERIES_FAILURE = 'FETCH_DELIVERIES_FAILURE',
  DELIVERY_LOADING = 'DELIVERY_LOADING',
  DELIVERY_SUCCESS = 'DELIVERY_SUCCESS',
  DELIVERY_FAILURE = 'DELIVERY_FAILURE',
  UPDATE_DELIVERY_STATUS = 'UPDATE_DELIVERY_STATUS',
  MAKE_DELIVERY_ACTIVE = 'MAKE_DELIVERY_ACTIVE',
}
